language: java
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
notifications:
  slack:
    secure: stZLPNETvgi1pKv+G0gvODz/jDOd4a7hcicbAEQyHqFfQuHYeTtbRpF3hjdI/EufWjsae+TptXVEchgNLYTd/7zfMwUdrjWGr7Q53B/dgFEcJf3BxfhYSGfFjJ5XYHRYI8agFbNX0lOAOp5LUoD528mDLwh7LKInb/N5+8XP22jvbHdNtxd4B8IaJq9lSb8shzLKpxsEQyqr7qS6jcFGb5E8pAEorbnqv2hEugQXXMG2iRXRccGP4SrNa2keXOBgtVdPpzf4yLjXpCn8LZNIt/0UPfFTYvNDvoIn1UExwDyisKA7UnIfudtRROo3ohO7CTcgTFfliFqieU/4KU61gwKpOv4wk58vf54B5wWn8uhwvszMllPT4W2YSVADxMWtSX7bOKVbP+ygYv9Da3xoQdotARGzg5HLh8p51M53eeKD3hxdAE1AaYxgcPdDovPX7vTAVa6Gz1DtZhAi704bdb3ukeaJ1Ff5HPllnJU0Qy0BJ75/FH2BnjPnRuuDQ9ZGRif8CGfG4Tn8615cL4fgQLtXLD4zG9Qft4gDJjJNEGyX8DQGaG6jmQ1lK6Ock97oYjMootYg4UCkpDO4QdlrawhRjRtECY2uvq2KIxJiiOyoPDXs2UgMr0eMj9YrbtFwsqUxxuhlZwW+3rw+atTVFaiIA53CiM1pTjqM5b/RGhg=
